import Vue from 'vue';
import { Tabbar, TabbarItem } from 'vant';
import { Loading } from 'vant';
import { Image } from 'vant';
import { Toast } from 'vant';
import { Dialog } from 'vant';
import { NavBar } from 'vant';
import { ContactCard, ContactList, ContactEdit } from 'vant';
import { AddressList } from 'vant';
import { AddressEdit } from 'vant';
import { Cell, CellGroup } from 'vant';
import { SubmitBar } from 'vant';
import { Grid, GridItem } from 'vant';

Vue.use(Tabbar);
Vue.use(TabbarItem);
Vue.use(Loading);
Vue.use(Image);
Vue.use(Toast);
Vue.use(Dialog);
Vue.use(NavBar);
Vue.use(ContactCard);
Vue.use(ContactList);
Vue.use(ContactEdit);
Vue.use(AddressList);
Vue.use(AddressEdit);
Vue.use(Cell);
Vue.use(CellGroup);
Vue.use(SubmitBar);
Vue.use(Grid);
Vue.use(GridItem);
